# Generated by Django 4.2 on 2023-09-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_entity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
