# Generated by Django 4.0 on 2023-12-30 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_country_remove_user_email_and_more'),
        ('contracts', '0004_contract_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=100)),
                ('entidad', models.CharField(max_length=100)),
                ('objeto', models.CharField(max_length=255)),
                ('plazo_de_ejecucion', models.DateTimeField()),
                ('supervisor', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_lote', models.IntegerField()),
                ('numero_de_contrato', models.CharField(max_length=100)),
                ('numero_de_orden', models.IntegerField()),
                ('talla', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('asignado', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('fecha_recibido', models.DateTimeField()),
                ('historial', models.CharField(max_length=100)),
                ('novedad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_orden', models.IntegerField()),
                ('item', models.CharField(max_length=255)),
                ('valor_unitario', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('numero_de_contrato', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='ordenofwork',
            name='contract',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='OrdenOfWork',
        ),
    ]
