# Generated by Django 4.0 on 2024-01-07 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contratos_lotes_ordendetrabajo_personal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
