# Generated by Django 4.0 on 2024-02-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_ordendetrabajo_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satelites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=255)),
            ],
        ),
    ]
