# Generated by Django 4.0 on 2024-02-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_satelites'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='cantidad_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='unidades_en_progreso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='unidades_faltantes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='valor_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
