# Generated by Django 4.0 on 2024-02-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_contratos_unidades_cumplidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotes',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
